<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Material;
use Illuminate\Support\Carbon;

class MaterialSeeder extends Seeder
{
    /**
     * Seed comprehensive construction materials catalog with July 2026 market prices.
     */
    public function run(): void
    {
        $now = Carbon::create(2026, 7, 15, 12, 0, 0);

        $materials = [
            // 1. Abdichtung & Reaktivabdichtung
            [
                'name' => 'PCI Pecimor 2K Bitumen-Dickbeschichtung (30 Liter)',
                'sku' => 'MAT-PCI-2K-30L',
                'category' => 'Abdichtung & Reaktivabdichtung',
                'unit' => 'Stk',
                'unit_price' => 89.50,
                'supplier' => 'Baustoffhandel Süd',
                'notes' => 'Zwei-Komponenten-Bitumendickbeschichtung für Kellerwandabdichtung (PMBC)',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Remmers MB 2K Multi-Baudicht (25 kg)',
                'sku' => 'MAT-REM-MB2K',
                'category' => 'Abdichtung & Reaktivabdichtung',
                'unit' => 'Sack',
                'unit_price' => 128.50,
                'supplier' => 'Remmers Fachhandel',
                'notes' => 'Multifunktionale, bitumenfreie Reaktivabdichtung für Sockel und Keller',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Botament RD2 The Green 1 Reaktivabdichtung (20 kg)',
                'sku' => 'MAT-BOT-RD2-20KG',
                'category' => 'Abdichtung & Reaktivabdichtung',
                'unit' => 'Eimer',
                'unit_price' => 115.00,
                'supplier' => 'Botament Systems',
                'notes' => 'Schnellabbindende bitumenfreie 2K-Reaktivabdichtung ohne Grundierung',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Schomburg COMBIDICHT-2K Bitumen-Dickbeschichtung (30 kg)',
                'sku' => 'MAT-SCH-COMB2K',
                'category' => 'Abdichtung & Reaktivabdichtung',
                'unit' => 'Eimer',
                'unit_price' => 82.00,
                'supplier' => 'Schomburg Baustoffsysteme',
                'notes' => 'Polystyrolgefüllte 2K-Kunststoffmodifizierte Bitumendickbeschichtung',
                'last_price_update' => $now,
            ],
            [
                'name' => 'SikaIgolflex-201 Bitumen-Dickbeschichtung 2K (32 kg)',
                'sku' => 'MAT-SIK-201-32KG',
                'category' => 'Abdichtung & Reaktivabdichtung',
                'unit' => 'Eimer',
                'unit_price' => 94.50,
                'supplier' => 'Sika Deutschland',
                'notes' => 'Lösemittelfreie, faserverstärkte 2K Bitumen-Dickbeschichtung',
                'last_price_update' => $now,
            ],
            [
                'name' => 'PCI Seccoral 2K Schnelle Dichtungsschlämme (25 kg Set)',
                'sku' => 'MAT-PCI-SEC2K',
                'category' => 'Abdichtung & Reaktivabdichtung',
                'unit' => 'Set',
                'unit_price' => 89.00,
                'supplier' => 'PCI Augsburg',
                'notes' => 'Elastische Dichtungsschlämme für Balkone, Terrassen und Schwimmbecken',
                'last_price_update' => $now,
            ],

            // 2. Injektionstechnik & Rissverpressung
            [
                'name' => 'KÖSTER PU-Injektionsharz 2K Set (5 Liter)',
                'sku' => 'MAT-INJ-PU2K',
                'category' => 'Injektionstechnik & Rissverpressung',
                'unit' => 'Set',
                'unit_price' => 128.00,
                'supplier' => 'KÖSTER Bauchemie',
                'notes' => 'Drucklose und druckbehaftete Rissverpressung gegen drückendes Wasser',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Desoi Stahlpacker 10x100mm mit Greifkopf (100 Stk)',
                'sku' => 'MAT-DES-ST10X100',
                'category' => 'Injektionstechnik & Rissverpressung',
                'unit' => 'Karton',
                'unit_price' => 88.50,
                'supplier' => 'Desoi Injektionstechnik',
                'notes' => 'Hochdruck-Schraubpacker aus Verzinktem Stahl mit Einsetzventil',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Desoi Schlagpacker Kunststoff 12x110mm (100 Stk)',
                'sku' => 'MAT-DES-KS12X110',
                'category' => 'Injektionstechnik & Rissverpressung',
                'unit' => 'Karton',
                'unit_price' => 45.00,
                'supplier' => 'Desoi Injektionstechnik',
                'notes' => 'Niederdruck-Schlagpacker für Zementschlämme & Harzinjektion',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Sika Injection-201 CE Elastisches PU-Harz (20 kg)',
                'sku' => 'MAT-SIK-INJ201',
                'category' => 'Injektionstechnik & Rissverpressung',
                'unit' => 'Set',
                'unit_price' => 245.00,
                'supplier' => 'Sika Deutschland',
                'notes' => 'Dauerhaft elastisches PUR-Injektionsharz zur Rissabdichtung nach DIN EN 1504-5',
                'last_price_update' => $now,
            ],
            [
                'name' => 'WEBAC 1403 Flexibles PU-Injektionsharz (10 kg)',
                'sku' => 'MAT-WEB-1403-10KG',
                'category' => 'Injektionstechnik & Rissverpressung',
                'unit' => 'Set',
                'unit_price' => 168.00,
                'supplier' => 'WEBAC Chemie',
                'notes' => 'Niedrigviskoses PU-Verpressharz für Feuchterisse in Beton und Mauerwerk',
                'last_price_update' => $now,
            ],

            // 3. Beton- & Estrichsanierung
            [
                'name' => 'Ardex A 38 MIX Blitzzement-Estrich fertig gemischt (25 kg)',
                'sku' => 'MAT-ARD-A38MIX',
                'category' => 'Beton- & Estrichsanierung',
                'unit' => 'Sack',
                'unit_price' => 44.50,
                'supplier' => 'Ardex Baustoffsysteme',
                'notes' => 'Schnellbinde-Estrichfertigmischung, belegreif nach 4 Stunden',
                'last_price_update' => $now,
            ],
            [
                'name' => 'PCI Periplan Extra Nivelliermasse (25 kg)',
                'sku' => 'MAT-PCI-PERIPLAN',
                'category' => 'Beton- & Estrichsanierung',
                'unit' => 'Sack',
                'unit_price' => 38.90,
                'supplier' => 'PCI Augsburg',
                'notes' => 'Faserarmierte Bodenausgleichsmasse für Holz- und Mineraluntergründe',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Pagel V1/50 Vergussmörtel quellfähig (25 kg)',
                'sku' => 'MAT-PAG-V1-50',
                'category' => 'Beton- & Estrichsanierung',
                'unit' => 'Sack',
                'unit_price' => 29.80,
                'supplier' => 'Pagel Spezial-Beton',
                'notes' => 'Hochfester Präzisions-Vergussmörtel für Maschinenverankerung & Stützen',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Sika MonoTop-412 N PCC-Reparaturmörtel (25 kg)',
                'sku' => 'MAT-SIK-MT412N',
                'category' => 'Beton- & Estrichsanierung',
                'unit' => 'Sack',
                'unit_price' => 34.20,
                'supplier' => 'Sika Deutschland',
                'notes' => 'Faserverstärkter R4-Instandsetzungsmörtel für statisch relevante Betonbauteile',
                'last_price_update' => $now,
            ],

            // 4. Dämmung & Perimeter
            [
                'name' => 'XPS Dämmplatte 100mm WLG 035 Stufenfalz',
                'sku' => 'MAT-XPS-100MM',
                'category' => 'Dämmung & Perimeter',
                'unit' => 'm²',
                'unit_price' => 18.20,
                'supplier' => 'IsoBau GmbH',
                'notes' => 'Druckfeste Perimeterdämmung für Kelleraußenwände und Gründächer',
                'last_price_update' => $now,
            ],
            [
                'name' => 'XPS Dämmplatte 120mm WLG 035 Stufenfalz',
                'sku' => 'MAT-XPS-120MM',
                'category' => 'Dämmung & Perimeter',
                'unit' => 'm²',
                'unit_price' => 22.50,
                'supplier' => 'IsoBau GmbH',
                'notes' => 'Extrudierte Polystyrol-Hartschaumplatte für hohe Druckbelastung',
                'last_price_update' => $now,
            ],
            [
                'name' => 'XPS Dämmplatte 160mm WLG 035 Stufenfalz',
                'sku' => 'MAT-XPS-160MM',
                'category' => 'Dämmung & Perimeter',
                'unit' => 'm²',
                'unit_price' => 29.80,
                'supplier' => 'IsoBau GmbH',
                'notes' => 'Hocheffiziente Kellerwand-Perimeterdämmung gemäß KFW-Standard',
                'last_price_update' => $now,
            ],
            [
                'name' => 'EPS Sockeldämmplatte 100mm WLG 032',
                'sku' => 'MAT-EPS-SOC100',
                'category' => 'Dämmung & Perimeter',
                'unit' => 'm²',
                'unit_price' => 14.90,
                'supplier' => 'Austrotherm',
                'notes' => 'Wasserabweisende Spezialdämmplatte für den Spritzwasser-Sockelbereich',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Rockwool Steinwolle Dämmplatte 120mm WLG 035',
                'sku' => 'MAT-ROC-120MM',
                'category' => 'Dämmung & Perimeter',
                'unit' => 'm²',
                'unit_price' => 16.80,
                'supplier' => 'DEUTSCHE ROCKWOOL',
                'notes' => 'Nichtbrennbare Fassadendämmplatte A1 für Brandschutz & Schallschutz',
                'last_price_update' => $now,
            ],

            // 5. Drainage & Schutzsysteme
            [
                'name' => 'Dörken Delta-MS Noppenbahn 2,0m x 20m',
                'sku' => 'MAT-NOP-2X20',
                'category' => 'Drainage & Schutzsysteme',
                'unit' => 'Rolle',
                'unit_price' => 98.00,
                'supplier' => 'Dörken Delta',
                'notes' => 'Grundmauerschutzbahn mit hoher Druckfestigkeit von 250 kN/m²',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Dörken Delta-Geo-Drain TP Drainagesystem 2.0m x 12.5m',
                'sku' => 'MAT-DEL-GEODRAIN',
                'category' => 'Drainage & Schutzsysteme',
                'unit' => 'Rolle',
                'unit_price' => 145.00,
                'supplier' => 'Dörken Delta',
                'notes' => '3-schichtiges Schutz- und Drainagesystem mit aufkaschiertem Vlies für Dickbeschichtung',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Drainagerohr DN 100 gelocht mit Kokosmantel (50m)',
                'sku' => 'MAT-DRA-100-50M',
                'category' => 'Drainage & Schutzsysteme',
                'unit' => 'Rolle',
                'unit_price' => 185.00,
                'supplier' => 'Fränkische Rohrwerke',
                'notes' => 'Filtrationsstabiles Drainsysten für versickerungsfähige Böden',
                'last_price_update' => $now,
            ],
            [
                'name' => 'ACO Master Lichtschacht 100x100x40 cm mit Gitterrost',
                'sku' => 'MAT-ACO-LICHT100',
                'category' => 'Drainage & Schutzsysteme',
                'unit' => 'Stk',
                'unit_price' => 289.00,
                'supplier' => 'ACO Severin Ahlmann',
                'notes' => 'Druckwasserdicht montierbarer Kellerschacht aus GFK mit Zubehör',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Doyma Schachtfutter DN 100 Faserzement',
                'sku' => 'MAT-DOY-SF100',
                'category' => 'Drainage & Schutzsysteme',
                'unit' => 'Stk',
                'unit_price' => 24.50,
                'supplier' => 'Doyma Dichtungssysteme',
                'notes' => 'Einbauteil für wasserundurchlässige Betonwände (WU-Beton)',
                'last_price_update' => $now,
            ],

            // 6. Dichtbänder, Folien & Fugenabdichtung
            [
                'name' => 'PCI Lastogum Dichtfolie für Nassräume (25 kg)',
                'sku' => 'MAT-PCI-LASTO25',
                'category' => 'Dichtbänder & Fugenabdichtung',
                'unit' => 'Eimer',
                'unit_price' => 92.00,
                'supplier' => 'PCI Augsburg',
                'notes' => 'Flüssige Flächenabdichtung unter Fliesen und Platten in Bädern & Duschen',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Botament DB75 Elastisches Dichtband (50m Rolle)',
                'sku' => 'MAT-BAN-120-50M',
                'category' => 'Dichtbänder & Fugenabdichtung',
                'unit' => 'Rolle',
                'unit_price' => 62.50,
                'supplier' => 'Botament Systems',
                'notes' => 'Querelastisches Vlies-Dichtband für Wand-Boden-Anschlüsse',
                'last_price_update' => $now,
            ],
            [
                'name' => 'OTTOSEAL S70 Premium Naturstein-Silikon 310ml (Transparent)',
                'sku' => 'MAT-OTT-S70-310',
                'category' => 'Dichtbänder & Fugenabdichtung',
                'unit' => 'Stk',
                'unit_price' => 11.80,
                'supplier' => 'Otto Chemie',
                'notes' => 'Neutral vernetzender Silikon-Dichtstoff ohne Randzonenverschmutzung',
                'last_price_update' => $now,
            ],
            [
                'name' => 'illbruck ME508 Twin-Aktiv Folie mit Klebestreifen (25m x 100mm)',
                'sku' => 'MAT-ILL-ME508',
                'category' => 'Dichtbänder & Fugenabdichtung',
                'unit' => 'Rolle',
                'unit_price' => 48.90,
                'supplier' => 'Tremco CPG',
                'notes' => 'Feuchtevariable Fenster- und Fassaden-Anschlussfolie nach RAL-Güterichtlinie',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Doyma Curaflex Dichtungseinsatz DN 100 / Rohr 50-63mm',
                'sku' => 'MAT-DOY-CURA100',
                'category' => 'Dichtbänder & Fugenabdichtung',
                'unit' => 'Stk',
                'unit_price' => 165.00,
                'supplier' => 'Doyma Dichtungssysteme',
                'notes' => 'Ringraumdichtung gegen drückendes Wasser (EDPM / Edelstahl V2A)',
                'last_price_update' => $now,
            ],

            // 7. Trockenbau & Wandbaustoffe
            [
                'name' => 'Knauf Diamant Harte Gipsplatte 12,5mm (1200x600 mm)',
                'sku' => 'MAT-KNA-DIA125',
                'category' => 'Trockenbau & Wandbaustoffe',
                'unit' => 'Stk',
                'unit_price' => 10.20,
                'supplier' => 'Knauf Gips KG',
                'notes' => 'Schallschutz-, Feuchtraum- und Brandschutzplatte (DFH2IR)',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Knauf CW-75 Ständerprofil 0,6mm (3,00 m)',
                'sku' => 'MAT-KNA-CW75-3M',
                'category' => 'Trockenbau & Wandbaustoffe',
                'unit' => 'Stk',
                'unit_price' => 8.90,
                'supplier' => 'Knauf Gips KG',
                'notes' => 'Verzinktes C-Fassadenprofil für Trockenbauwände',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Rigips Bauplatte RB 12,5mm (2000x1250 mm)',
                'sku' => 'MAT-RIG-RB125',
                'category' => 'Trockenbau & Wandbaustoffe',
                'unit' => 'Stk',
                'unit_price' => 9.40,
                'supplier' => 'Saint-Gobain Rigips',
                'notes' => 'Standard Gipsplatte für Wand- und Deckenbekleidungen',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Fermacell Gipsfaser-Platte 12,5mm (1500x1000 mm)',
                'sku' => 'MAT-FER-125MM',
                'category' => 'Trockenbau & Wandbaustoffe',
                'unit' => 'Stk',
                'unit_price' => 14.80,
                'supplier' => 'Fermacell / James Hardie',
                'notes' => 'Extreme Stabilität und hoher Brandschutz für Holzbau und Sanierung',
                'last_price_update' => $now,
            ],

            // 8. Verbrauchsmaterial & Arbeitsschutz
            [
                'name' => 'Nitril-Schutzhandschuhe Heavy Duty (100er Box)',
                'sku' => 'MAT-ALL-NITRIL100',
                'category' => 'Verbrauchsmaterial & Arbeitsschutz',
                'unit' => 'Box',
                'unit_price' => 14.50,
                'supplier' => 'Ansell Safety',
                'notes' => 'Chemikalien- und reißfeste Einweg-Nitrilhandschuhe Schwarz',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Abdeckvlies rutschhemmend 220g/m² (1m x 50m)',
                'sku' => 'MAT-PRO-VLIES220',
                'category' => 'Verbrauchsmaterial & Arbeitsschutz',
                'unit' => 'Rolle',
                'unit_price' => 38.00,
                'supplier' => 'ProfiProtect',
                'notes' => 'Saugestarkes Malervlies mit PE-Folie gegen Durchfeuchten',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Gewebe-Big-Bag 1000kg für Bauschutt (90x90x110cm)',
                'sku' => 'MAT-BAG-1000KG',
                'category' => 'Verbrauchsmaterial & Arbeitsschutz',
                'unit' => 'Stk',
                'unit_price' => 12.50,
                'supplier' => 'Verpackungsprofi',
                'notes' => 'Extrem belastbarer Gewebesack mit 4 Hebeschlaufen (SWL 1,0 t)',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Collomix SDS-Plus Rührquirl MK 120mm',
                'sku' => 'MAT-COL-QUIRL120',
                'category' => 'Verbrauchsmaterial & Arbeitsschutz',
                'unit' => 'Stk',
                'unit_price' => 24.90,
                'supplier' => 'Collomix',
                'notes' => 'Mischwerkzeuge für zähe und schwere Mörtel, Harze & Beschichtungen',
                'last_price_update' => $now,
            ],
            [
                'name' => 'Gewebe-Entsorgungssäcke 120 Liter extrem reißfest (20 Stk)',
                'sku' => 'MAT-SACK-120L-20',
                'category' => 'Verbrauchsmaterial & Arbeitsschutz',
                'unit' => 'Pack',
                'unit_price' => 22.00,
                'supplier' => 'ProfiProtect',
                'notes' => 'Heavy Duty Bauschuttsäcke für scharfe Fliesen, Betonsteine und Putzreste',
                'last_price_update' => $now,
            ],
        ];

        foreach ($materials as $data) {
            Material::updateOrCreate(
                ['sku' => $data['sku']],
                $data
            );
        }

        $this->command->info("✅ " . count($materials) . " Materialpreise (Stand Juli 2026) erfolgreich geseeded!");
    }
}
